name: Deploy to Another Branch

on:
  push:
    branches:
      - main  # Trigger the action when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install dependencies and build (if needed)
      run: |
        # Run your build steps here (if necessary)
        npm install
        npm run build

    - name: Copy files to another branch
      run: |
        # Configure Git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Create a new directory for the deployment
        git fetch origin deploy-branch
        git checkout -b deploy-branch origin/deploy-branch || git checkout --orphan deploy-branch

        # Remove all existing files from the deploy-branch
        rm -rf ./*

        # Copy the contents from the dist folder to the current directory
        cp -r ./dist/* ./

        # Add all the files to git and commit the changes
        git add .
        git commit -m "Deploying updated build from main"

        # Push the changes to deploy-branch
        git push origin deploy-branch --force
