name: Deploy to Another Branch

on:
  push:
    branches:
      - main  # Trigger the action when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install dependencies and build (if needed)
      run: |
        # Run your build steps here (if necessary)
        npm install
        npm run build

    - name: Copy files to another branch
      run: |
        # Configure Git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Create a new directory for the deployment
        git fetch origin deploy
        git checkout -b deploy origin/deploy || git checkout --orphan deploy

        # Remove all existing files from the deploy
        # rm -rf $(find -type d -maxdepth 1 ! -name ".git" ! -name "dist" ! -name "." ! -name "..")
        rm -r $(find -type f -maxdepth 1)
        
        rm -rf .github scripts src

        # Copy the contents from the dist folder to the current directory
        cp -r ./dist/* ./
        rm -rf dist/

        # Add all the files to git and commit the changes
        git add .
        git commit -m "Deploying updated build from main"

        # Push the changes to deploy
        git push origin deploy --force
